### PR TITLE
Feat: Foundry tooling

### PR DESCRIPTION
**Pull request by sambacha**
## Feature: Foundry support

This PR adds: 

- foundry configuration (foundry.toml)
- Justfile script (task runner/Makefile but without its idiosyncrasies)

With Foundry and Just installed you can simply

```shell
just build
```

### Pragma bump

[0.8.13 sees ViaIR come into production, see solidity documentation for more information](https://docs.soliditylang.org/en/develop/ir-breaking-changes.html?highlight=viair)

### Benchmarks  

<pre>
200 OPTIMIZER RUNS
VIA_IR=TRUE
SOLIDITY=0.8.10
Compiler run successful
name             size (bytes)
-----------------------------
Gem                  4582
GemFab               5762
</pre>

<pre>
200 OPTIMIZER RUNS
VIA_IR=TRUE
SOLIDITY=0.8.13
Compiler run successful
name             size (bytes)
-----------------------------
Gem                  4410
GemFab             5439
</pre>

### CODE REVIEW

**Comment by nmushegian** [comment]
Thank you for this PR
Can you briefly explain why we would want to use `just` instead of just `make` or similar
Foundry support is good I think

**Comment by sambacha** [comment]
> Thank you for this PR Can you briefly explain why we would want to use `just` instead of just `make` or similar Foundry support is good I think

# `just` do it

> high-level benefits of using `just` and why `make` is ill-suited 

- [make idiosyncrasies](#make-idiosyncrasies)
- [Project Benefits](#project-benefits)
- [Composability: using Node.js `package.json` for script compatibility](#composability-example--using-nodejs--packagejson--for-script-compatibility)
- [`ENV` support](#-env--support)
  * [Dotenv Load](#dotenv-load)
  * [Export](#export)
  * [Positional Arguments](#positional-arguments)

## `make` idiosyncrasies

`make` has some behaviors which are confusing, complicated, or make it unsuitable for use as a general command/CI runner.

Example:  under some circumstances, `make` won't actually run the commands in a recipe. For example, if you have a file called `test` and the following makefile:

```make
test:
  ./test
```

`make` will refuse to run your tests:

```sh
$ make test
make: `test' is up to date.
```

`make` assumes that the `test` recipe produces a file called `test`. Since this file exists and the recipe has no other dependencies, `make` thinks that it doesn't have anything to do and exits.

To be fair, this behavior is desirable when using `make` as a build system, but not when using it as a command runner. You can disable this behavior for specific targets using `make`'s built-in [`.PHONY` target name](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html), but the syntax is verbose and can be hard to remember. 

The explicit list of phony targets, written separately from the recipe definitions, also introduces the risk of accidentally defining a new non-phony target. In `just`, all recipes are treated as if they were phony.

Other examples of `make`'s idiosyncrasies include the difference between `=` and `:=` in assignments, the confusing error messages that are produced if you mess up your makefile, needing `$$` to use environment variables in recipes, and incompatibilities between different flavors of `make`.

### Project Benefits

There are probably different commands to test, build, lint, deploy, and the like, and having them all in one place is useful and cuts down on the time you have to spend telling people which commands to run and how to type them.

And, with an easy place to put commands, it's likely that you'll come up with other useful things which are part of the project's collective wisdom, but which aren't written down anywhere, like the arcane commands needed for some part of your revision control workflow, install all your project's dependencies, or all the random flags you might need to pass to the build system.


### Composability example: using Node.js `package.json` for script compatibility

The following export statement gives `just` recipes access to local Node module binaries, and makes `just` recipe commands behave more like `script` entries in Node.js `package.json` files:

```make
export PATH := "./node_modules/.bin:" + env_var('PATH')
```

### `ENV` support

#### Dotenv Load

If `dotenv-load` is `true`, a `.env` file will be loaded if present. Defaults to `false`.

#### Export

The `export` setting causes all `just` variables to be exported as environment variables. Defaults to `false`.

```make
set export

a := "hello"

@foo b:
  echo $a
  echo $b
```

```sh
$ just foo goodbye
hello
goodbye
```

#### Positional Arguments

If `positional-arguments` is `true`, recipe arguments will be passed as positional arguments to commands. For linewise recipes, argument `$0` will be the name of the recipe.

For example, running this recipe:

```make
set positional-arguments

@foo bar:
  echo $0
  echo $1
```

Will produce the following output:

```sh
$ just foo hello
foo
hello
```


---
The bulk of information found here was sourced directly from the projects `README` file
[1]: [https://github.com/casey/just](https://github.com/casey/just) Accessed 2022.04.08 README.md

**Comment by sambacha** [comment]
> > Thank you for this PR Can you briefly explain why we would want to use `just` instead of just `make` or similar Foundry support is good I think
> 
> # `just` do it
> > high-level benefits of using `just` and why `make` is ill-suited
> 
> * [make idiosyncrasies](#make-idiosyncrasies)
> * [Project Benefits](#project-benefits)
> * [Composability: using Node.js `package.json` for script compatibility](#composability-example--using-nodejs--packagejson--for-script-compatibility)
> * [`ENV` support](#-env--support)
>   
>   * [Dotenv Load](#dotenv-load)
>   * [Export](#export)
>   * [Positional Arguments](#positional-arguments)
> 
> ## `make` idiosyncrasies
> `make` has some behaviors which are confusing, complicated, or make it unsuitable for use as a general command/CI runner.
> 
> Example: under some circumstances, `make` won't actually run the commands in a recipe. For example, if you have a file called `test` and the following makefile:
> 
> ```makefile
> test:
>   ./test
> ```
> 
> `make` will refuse to run your tests:
> 
> ```shell
> $ make test
> make: `test' is up to date.
> ```
> 
> `make` assumes that the `test` recipe produces a file called `test`. Since this file exists and the recipe has no other dependencies, `make` thinks that it doesn't have anything to do and exits.
> 
> To be fair, this behavior is desirable when using `make` as a build system, but not when using it as a command runner. You can disable this behavior for specific targets using `make`'s built-in [`.PHONY` target name](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html), but the syntax is verbose and can be hard to remember.
> 
> The explicit list of phony targets, written separately from the recipe definitions, also introduces the risk of accidentally defining a new non-phony target. In `just`, all recipes are treated as if they were phony.
> 
> Other examples of `make`'s idiosyncrasies include the difference between `=` and `:=` in assignments, the confusing error messages that are produced if you mess up your makefile, needing `$$` to use environment variables in recipes, and incompatibilities between different flavors of `make`.
> 
> ### Project Benefits
> There are probably different commands to test, build, lint, deploy, and the like, and having them all in one place is useful and cuts down on the time you have to spend telling people which commands to run and how to type them.
> 
> And, with an easy place to put commands, it's likely that you'll come up with other useful things which are part of the project's collective wisdom, but which aren't written down anywhere, like the arcane commands needed for some part of your revision control workflow, install all your project's dependencies, or all the random flags you might need to pass to the build system.
> 
> ### Composability example: using Node.js `package.json` for script compatibility
> The following export statement gives `just` recipes access to local Node module binaries, and makes `just` recipe commands behave more like `script` entries in Node.js `package.json` files:
> 
> ```makefile
> export PATH := "./node_modules/.bin:" + env_var('PATH')
> ```
> 
> ### `ENV` support
> #### Dotenv Load
> If `dotenv-load` is `true`, a `.env` file will be loaded if present. Defaults to `false`.
> 
> #### Export
> The `export` setting causes all `just` variables to be exported as environment variables. Defaults to `false`.
> 
> ```makefile
> set export
> 
> a := "hello"
> 
> @foo b:
>   echo $a
>   echo $b
> ```
> 
> ```shell
> $ just foo goodbye
> hello
> goodbye
> ```
> 
> #### Positional Arguments
> If `positional-arguments` is `true`, recipe arguments will be passed as positional arguments to commands. For linewise recipes, argument `$0` will be the name of the recipe.
> 
> For example, running this recipe:
> 
> ```makefile
> set positional-arguments
> 
> @foo bar:
>   echo $0
>   echo $1
> ```
> 
> Will produce the following output:
> 
> ```shell
> $ just foo hello
> foo
> hello
> ```
> 
> The bulk of information found here was sourced directly from the projects `README` file [1]: [casey/just](https://github.com/casey/just) Accessed 2022.04.08 README.md

Use case: using the built-in support for `.env` configuration, a justfile will enable you to immediately use your configured RPC, etc. whereas `foundry.toml` does not offer this configuration/settings option for loading such api keys.

**Comment by nmushegian** [comment]
That documentation was not really helpful for me to understand why we need all of this
Consider I could, for example, post the documentation for a different programming language, and all the ways it would be a better choice than javascript

I think a good exercise would be to ask 'what is the smallest PR necessary to make foundry work'

**Comment by sambacha** [comment]
> That documentation was not really helpful for me to understand why we need all of this Consider I could, for example, post the documentation for a different programming language, and all the ways it would be a better choice than javascript
> 
> I think a good exercise would be to ask 'what is the smallest PR necessary to make foundry work'

you asked *why* you would want to use it over make, implying that if not using justfile you would be using something like a Makefile as a tooling convenience. 

I included the justfile to help ease transition from those more familiar with a dapptools environment. Also, Foundry is on a nightly release schedule, some commands may change, etc, so it is generally helpful to have a task runner in which developers can quickly utilize to get started.

**Comment by sambacha** [comment]
> That documentation was not really helpful for me to understand why we need all of this Consider I could, for example, post the documentation for a different programming language, and all the ways it would be a better choice than javascript
> 
> I think a good exercise would be to ask 'what is the smallest PR necessary to make foundry work'

I have amended my initial commit, I do not think a patch bump in the versioning is required for this.

**Comment by nmushegian** [comment]
ty
Also I noticed this was gemfab not dmap -- I think I'm gonna be more relaxed about gemfab PRs so keep em coming just keep things small so I can understand things

**Comment by sambacha** [comment]
@nmushegian literally just pushed another commit to fix the configuration of foundry and hardhat so that they are in sync

**Pull request merged**
