### PR TITLE
build(hardhat): sync with foundry settings

### PR DESCRIPTION
**Pull request by sambacha**
This PR covers a commit that was not included in my last PR. namely it:

- configures hardhat to use the same settings as Foundry's configuration. 
- uses the `sol` directory for sourcing contract code for foundry to build
- fixes hardhat.config.ts to use proper types
- adds repo information to the npm package manifest file

### CODE REVIEW

**Comment by sambacha** [comment]
Apologies for 2 PR's @nmushegian

**Comment by nmushegian** [comment]
sweet ty
I just gave you write permissions for this repo
This way you can have a branch inside this repo and it will be less annoying
Instead we just have push protection for develop branch

now reviewing the PR

**Comment by nmushegian** [comment]
Can we drop the package.json changes, otherwise lgtm

**Comment by sambacha** [comment]
Wr will get me there eventually, yes give me a few mins not at my workstation currently

**Review by sambacha — COMMENTED** [review]
💯

**Comment by sambacha** [comment]
> Can we drop the package.json changes, otherwise lgtm
🟢

**Pull request closed without merging**
